

CREATE SCHEMA AUTHORIZATION EPS;
-- To create a table called availability in the EPS  schemas, use the following syntax:

CREATE TABLE EPS.AVAILABILITY
	(HOTEL_ID INT NOT NULL, BOOKING_DATE DATE NOT NULL, ROOMS_TAKEN INT,
	CONSTRAINT HOTELAVAIL_PK PRIMARY KEY (HOTEL_ID, BOOKING_DATE));